/*
    fact_snapshot_*
    ---------------
    Macro-driven periodic snapshot facts, siblings to the scd2_* dimension
    pattern in scd2_dimension.sql. Each fact is declared ONCE in
    vars.fact_snapshots (dbt_project.yml); every model / test file is a
    one-line shim generated by fact_snapshot_generate_shims (see
    fact_snapshot_codegen.sql).

        vars:
          fact_snapshots:
            - name: fact_inventory_snapshot   # marker; also the consumption table name
              source: stg_inventory           # staging model ref'd by the history model
              natural_key: [warehouse_id, sku_id]   # string, or list for composite keys
              # everything below is optional (defaults shown):
              # snapshot_date_column: snapshot_date      # becomes the snapshot_date column (DATE)
              # surrogate_key:        fact_inventory_snapshot_sk   # <name>_sk
              # dist_column:          warehouse_id       # first natural key column
              # natural_key_cast:     nvarchar(400)      # cast for the surrogate-key concat
              # dedupe_order_by:      (select 0)          # tie-break inside one snapshot date
              # volume_guard_factor:  0.5                 # gate: latest snapshot vs trailing avg
              # volume_guard_window:  7                    # trailing snapshot count
              # presentation_exclude: [_batch_id, _loaded_at]
              #   columns omitted from fact_<name>__published and the consumption table

    HOW THIS DIFFERS FROM scd2_dimension:
      - A periodic snapshot fact APPENDS EVERY ROW for each new snapshot
        date, not just rows that changed - that repetition is the entire
        point of a snapshot fact (it lets you trend a measure even when
        nothing changed). There is no hash/change-detection column.
      - Grain is (natural key, snapshot_date), not an SCD2 valid_from /
        valid_to interval - so there is no LEAD()-derived candidate view.
        The history table itself is both the storage AND the gate-test
        target; fact_snapshot_published just applies the approval filter.
      - Everything else - insert-only history, batch approval via
        audit.fact_approved_batches, purge-unapproved pre-hook, drift-safe
        attribute resolution, CTAS+RENAME consumption table - mirrors the
        SCD2 machinery exactly (and shares scd2_resolve_attributes /
        scd2_synapse_ddl_type / the scd2__key_* helpers, which are already
        generic over any cfg dict with key_cols / presentation_exclude /
        history_model fields).

    Shim files (written by fact_snapshot_generate_shims into generated/ dirs):

        models/fact/generated/fact_inventory_snapshot__history.sql
            {{ fact_snapshot_history('fact_inventory_snapshot') }}
        models/fact/generated/fact_inventory_snapshot__published.sql
            {{ fact_snapshot_published('fact_inventory_snapshot') }}
        tests/generated/fact_inventory_snapshot__gates.sql
            {{ fact_snapshot_gate_test('fact_inventory_snapshot') }}

    Wire-up in dbt_project.yml (alongside the existing scd2 hooks):

        on-run-start:
          - "{{ fact_snapshot_generate_shims() }}"
          - "{{ fact_snapshot_bootstrap_audit() }}"
        on-run-end:
          - "{{ fact_snapshot_approve_batches(results) }}"

    Use 'dbt build' (not 'dbt run') so gate tests execute and batches
    actually get approved - identical requirement to the SCD2 side.
*/


{#- Look up one fact in vars.fact_snapshots, validate, apply defaults.
    Returns a dict shaped like scd2_dimension_config's, so the scd2__key_*,
    scd2__surrogate_key_expr and scd2__presentation_columns helpers work
    unmodified against it. -#}
{% macro fact_snapshot_config(marker) %}
    {%- set facts = var('fact_snapshots', []) -%}
    {%- set hit = namespace(d=none) -%}
    {%- for d in facts -%}
        {%- if d.get('name') == marker -%}{%- set hit.d = d -%}{%- endif -%}
    {%- endfor -%}
    {%- if hit.d is none -%}
        {{ exceptions.raise_compiler_error(
            "fact_snapshot: no fact named '" ~ marker ~ "' in vars.fact_snapshots. " ~
            "Add an entry to dbt_project.yml, minimum: " ~
            "{name: " ~ marker ~ ", source: <staging model>, natural_key: <column or list>}") }}
    {%- endif -%}
    {%- set d = hit.d -%}
    {%- if not d.get('source') or not d.get('natural_key') -%}
        {{ exceptions.raise_compiler_error(
            "fact_snapshot: fact '" ~ marker ~ "' must define both 'source' and 'natural_key' " ~
            "in vars.fact_snapshots.") }}
    {%- endif -%}
    {%- set nk = d.get('natural_key') -%}
    {%- set key_cols = [nk] if nk is string else nk | list -%}
    {%- set pres_excl = d.get('presentation_exclude', []) -%}
    {%- set pres_excl = [pres_excl] if pres_excl is string else pres_excl | list -%}
    {%- set pres_excl = pres_excl | map('lower') | list -%}
    {%- set dist_col = d.get('dist_column', key_cols[0]) -%}
    {%- set protected = (key_cols | map('lower') | list) + ['snapshot_date'] -%}
    {%- for col in pres_excl -%}
        {%- if col in protected -%}
            {{ exceptions.raise_compiler_error(
                "fact_snapshot: fact '" ~ marker ~ "' cannot exclude '" ~ col ~
                "' via presentation_exclude (natural keys and snapshot_date are required " ~
                "in the published view).") }}
        {%- endif -%}
        {%- if col == dist_col | lower -%}
            {{ exceptions.raise_compiler_error(
                "fact_snapshot: fact '" ~ marker ~ "' cannot exclude dist_column '" ~ dist_col ~
                "' via presentation_exclude - the consumption-table CTAS requires " ~
                "DISTRIBUTION = HASH(" ~ dist_col ~ ").") }}
        {%- endif -%}
    {%- endfor -%}
    {%- do return({
        'marker':          marker,
        'source':          d.get('source'),
        'key_cols':        key_cols,
        'change_col':      d.get('snapshot_date_column', 'snapshot_date'),
        'sk':              d.get('surrogate_key', marker ~ '_sk'),
        'dist_col':        dist_col,
        'key_cast':        d.get('natural_key_cast', 'nvarchar(400)'),
        'dedupe_order':    d.get('dedupe_order_by', '(select 0)'),
        'volume_factor':   d.get('volume_guard_factor', 0.5),
        'volume_window':   d.get('volume_guard_window', 7),
        'presentation_exclude': pres_excl,
        'history_model':   marker ~ '__history',
        'published_model': marker ~ '__published'
    }) -%}
{% endmacro %}


{#- History and gate models must use the default dbt object name (no alias) -
    approval and purge key off model_name / relation.identifier, same
    requirement as scd2_assert_alias_forbidden. -#}
{% macro fact_snapshot_assert_alias_forbidden() %}
    {%- set configured = config.get('alias') -%}
    {%- if configured is not none and configured | trim != '' and configured != model.name -%}
        {{ exceptions.raise_compiler_error(
            "fact_snapshot: '" ~ model.name ~ "' must not set a dbt alias (found alias='" ~
            configured ~ "'). Approval, purge, and audit tables key off the model name. " ~
            "Remove alias from dbt_project.yml for this model.") }}
    {%- endif -%}
{% endmacro %}


{#- The published (consumption) view must alias to the fact marker,
    matching the consumption table refreshed by CTAS. -#}
{% macro fact_snapshot_assert_published_alias(marker) %}
    {%- set configured = config.get('alias') -%}
    {%- if configured != marker -%}
        {{ exceptions.raise_compiler_error(
            "fact_snapshot: published model '" ~ model.name ~ "' must have alias='" ~ marker ~
            "' (the consumption name). Found alias='" ~ configured ~
            "'. Remove conflicting alias config from dbt_project.yml.") }}
    {%- endif -%}
{% endmacro %}


{#
    Insert-only periodic snapshot fact. Every deduped row from the source
    for each NEW snapshot date is appended - unlike scd2_history there is no
    hash comparison against prior state, because repeating unchanged rows
    every period is the defining property of a snapshot fact.
#}
{% macro fact_snapshot_history(marker) %}
{%- set cfg = fact_snapshot_config(marker) -%}
{{ fact_snapshot_assert_alias_forbidden() }}
{{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='ignore',
    dist='HASH(' ~ cfg.dist_col ~ ')',
    index='CLUSTERED COLUMNSTORE INDEX',
    unique_key=cfg.sk,
    pre_hook="{{ fact_snapshot_purge_unapproved(this) }}",
    tags=['fact_snapshot_history'],
    meta={'fact_snapshot_model': marker}
) }}

{#- Drift-safe attribute resolution: union of staging and history columns.
    Runs any additive ALTERs as a side effect (real runs only). Shared with
    the SCD2 side - it only needs a source/history relation and column
    lists, nothing dimension-specific. -#}
{%- set attrs = scd2_resolve_attributes(
        source_relation   = ref(cfg.source),
        history_relation  = this,
        source_exclude    = cfg.key_cols + [cfg.change_col],
        history_meta_cols = [cfg.sk] + cfg.key_cols + ['snapshot_date', '_batch_id', '_loaded_at']
) -%}

with source as (

    select
        {{ scd2__key_list(cfg) }},
        {{ cfg.change_col }}{% if attrs.source_projection %},
        {{ attrs.source_projection | join(',\n        ') }}{% endif %}
    from {{ ref(cfg.source) }}

    {% if is_incremental() %}
    -- Only pull snapshot dates newer than the latest one already loaded.
    -- This is a FULL periodic snapshot: every row for a new date is
    -- appended, not just rows that changed since the prior snapshot.
    where {{ cfg.change_col }} > (
        select coalesce(max(snapshot_date), convert(date, '1900-01-01', 23))
        from {{ this }}
    )
    {% endif %}

),

-- Exactly one row per (natural key, snapshot date) - grain enforcement in
-- case the source ever emits duplicate rows for a key within one snapshot
deduped as (

    select *
    from (
        select
            s.*,
            row_number() over (
                partition by {{ scd2__key_list(cfg, 's') }}, s.{{ cfg.change_col }}
                order by {{ cfg.dedupe_order }}
            ) as _rn
        from source s
    ) x
    where _rn = 1

)

select
    {{ scd2__surrogate_key_expr(cfg) }} as {{ cfg.sk }},

    {{ scd2__key_list(cfg) }},
    {{ cfg.change_col }} as snapshot_date{% if attrs.names %},
    {{ attrs.names | join(',\n    ') }}{% endif %},

    cast('{{ invocation_id }}' as varchar(64)) as _batch_id,
    convert(datetime2(0), '{{ run_started_at.strftime("%Y-%m-%dT%H:%M:%S") }}', 126) as _loaded_at

from deduped
{% endmacro %}


{#
    Approval-gated logical view. No LEAD()/window derivation is needed -
    the grain already IS (natural key, snapshot_date), so this is just the
    approved-batches filter plus the presentation projection. Consumers
    read the <marker> consumption TABLE that fact_snapshot_refresh_published
    rebuilds from this view (same CTAS+RENAME pattern as scd2_published).
#}
{% macro fact_snapshot_published(marker) %}
{%- set cfg = fact_snapshot_config(marker) -%}
{%- set yaml_alias = config.get('alias') -%}
{%- if yaml_alias is not none and yaml_alias | trim != '' and yaml_alias != marker -%}
    {{ exceptions.raise_compiler_error(
        "fact_snapshot: published model '" ~ model.name ~ "' cannot use alias='" ~ yaml_alias ~
        "'. It must alias to the consumption name '" ~ marker ~ "'.") }}
{%- endif -%}
{{ config(
    materialized='view',
    alias=marker,
    pre_hook="{{ fact_snapshot_prepare_published_view(this) }}",
    tags=['fact_snapshot_published'],
    meta={'fact_snapshot_model': marker}
) }}
{{ fact_snapshot_assert_published_alias(marker) }}

select
    {{ scd2__presentation_columns(cfg, 'a') | join(',\n    ') }}
from {{ ref(cfg.history_model) }} a
where exists (
    select 1
    from audit.fact_approved_batches ab
    where ab.model_name = '{{ cfg.history_model }}'
      and ab.batch_id   = a._batch_id
)
{% endmacro %}


{#
    Single gating test per fact, run against the history model directly
    (it IS the approved+pending world - there is no separate candidate
    view because there is no derived valid_to/is_current to test).

    Checks:
      1. duplicate surrogate key                 (grain violation: key + snapshot_date)
      2. NULL surrogate key / natural key / snapshot_date
      3. completeness: every key in the latest source extract has a row
         in the latest fact snapshot for that same date (catches partial
         or truncated loads - this replaces SCD2's hash reconciliation,
         since a snapshot fact has no "current" row concept)
      4. volume guard: latest snapshot vs trailing average row count
#}
{% macro fact_snapshot_gate_test(marker) %}
{%- set cfg = fact_snapshot_config(marker) -%}
{{ fact_snapshot_assert_alias_forbidden() }}
{{ config(
    severity='error',
    store_failures=true,
    schema='audit',
    tags=['fact_snapshot_gate'],
    meta={'fact_snapshot_model': marker}
) }}

with fact as (

    select * from {{ ref(cfg.history_model) }}

),

latest_extract as (

    select {{ scd2__key_list(cfg) }}
    from {{ ref(cfg.source) }}
    where {{ cfg.change_col }} = (
        select max({{ cfg.change_col }}) from {{ ref(cfg.source) }}
    )

),

latest_snapshot as (

    select {{ scd2__key_list(cfg) }}
    from fact
    where snapshot_date = (
        select max(snapshot_date) from fact
    )

),

grain_violations as (

    select
        'duplicate surrogate key (grain violation: key + snapshot_date)' as failure_reason,
        cast({{ cfg.sk }} as nvarchar(400)) as offending_key
    from fact
    group by {{ cfg.sk }}
    having count(*) > 1

),

null_violations as (

    select
        'null surrogate key, natural key or snapshot_date' as failure_reason,
        {{ scd2__key_display(cfg) }} as offending_key
    from fact
    where {{ cfg.sk }} is null
       or snapshot_date is null
       {% for k in cfg.key_cols %}or {{ k }} is null
       {% endfor %}
),

completeness as (

    select
        'missing from latest snapshot vs latest source extract' as failure_reason,
        {{ scd2__key_display(cfg, 'l') }} as offending_key
    from latest_extract l
    left join latest_snapshot c
        on {{ scd2__key_join(cfg, 'c', 'l') }}
    where c.{{ cfg.key_cols[0] }} is null

),

volume_guard as (

    -- latest snapshot must be at least volume_guard_factor of the trailing
    -- volume_guard_window-snapshot average; catches truncated loads before
    -- they pollute the fact
    select
        'volume anomaly: latest snapshot below trailing average threshold' as failure_reason,
        cast(null as nvarchar(400)) as offending_key
    where (
        select count(*) from latest_snapshot
    ) < {{ cfg.volume_factor }} * coalesce((
        select avg(cast(cnt as float))
        from (
            select top {{ cfg.volume_window }} count(*) as cnt
            from fact
            group by snapshot_date
            order by snapshot_date desc
        ) recent
    ), 0)

)

select failure_reason, offending_key from grain_violations
union all
select failure_reason, offending_key from null_violations
union all
select failure_reason, offending_key from completeness
union all
select failure_reason, offending_key from volume_guard
{% endmacro %}
