/*
    fact_snapshot_generate_shims
    -----------------------------
    dbt-native shim generation for periodic snapshot facts, sibling to
    scd2_generate_shims (scd2_codegen.sql). Define facts once in
    vars.fact_snapshots and run:

      dbt run-operation fact_snapshot_generate_shims                # write_file runtimes
      dbt --quiet run-operation fact_snapshot_generate_shims | sh    # stock dbt-core

    This writes (or updates) one-line shim files:
      - models/fact/generated/<name>__history.sql
      - models/fact/generated/<name>__published.sql
      - tests/generated/<name>__gates.sql

    (No <name>__candidate.sql - a snapshot fact's grain is (natural key,
    snapshot_date), not an SCD2 valid_from/valid_to interval, so there is
    no window-function derivation that needs its own test target. The gate
    test runs directly against <name>__history.)

    Optional docs yaml is also generated:
      - models/fact/generated/fact_snapshot_generated_models.yml

    Wire into dbt_project.yml alongside the existing scd2 hook:

        on-run-start:
          - "{{ fact_snapshot_generate_shims() }}"
          - "{{ fact_snapshot_bootstrap_audit() }}"

    Same runtime note as scd2_generate_shims: stock dbt-core has no
    Jinja-accessible file-write context function, so on standard runtimes
    this prints a POSIX script to pipe through sh from the project root.
*/

{% macro fact_snapshot_markers() %}
    {%- set facts = var('fact_snapshots', []) -%}
    {%- set markers = [] -%}
    {%- for d in facts -%}
        {%- if not d.get('name') -%}
            {{ exceptions.raise_compiler_error(
                "fact_snapshot_generate_shims: every vars.fact_snapshots entry must define 'name'.") }}
        {%- endif -%}
        {%- if not modules.re.match('^[A-Za-z][A-Za-z0-9_]*$', d.get('name')) -%}
            {{ exceptions.raise_compiler_error(
                "fact_snapshot_generate_shims: fact name '" ~ d.get('name') ~
                "' must match ^[A-Za-z][A-Za-z0-9_]*$ (it becomes file and table names).") }}
        {%- endif -%}
        {%- if not d.get('source') or not d.get('natural_key') -%}
            {{ exceptions.raise_compiler_error(
                "fact_snapshot_generate_shims: fact '" ~ d.get('name') ~
                "' must define both 'source' and 'natural_key'.") }}
        {%- endif -%}
        {%- if d.get('name') not in markers -%}
            {%- do markers.append(d.get('name')) -%}
        {%- endif -%}
    {%- endfor -%}
    {%- do return(markers) -%}
{% endmacro %}


{% macro fact_snapshot_generate_shims(
    model_dir='models/fact/generated',
    test_dir='tests/generated',
    docs_yaml_path='models/fact/generated/fact_snapshot_generated_models.yml'
) %}
    {%- if not execute -%}
        {%- do return(none) -%}
    {%- endif -%}

    {%- set markers = fact_snapshot_markers() -%}
    {%- set header = '-- generated by dbt run-operation fact_snapshot_generate_shims' -%}

    {%- set files = [] -%}
    {%- for marker in markers -%}
        {%- do files.append([model_dir ~ '/' ~ marker ~ '__history.sql',
                             header ~ '\n' ~ "{{ fact_snapshot_history('" ~ marker ~ "') }}" ~ '\n']) -%}
        {%- do files.append([model_dir ~ '/' ~ marker ~ '__published.sql',
                             header ~ '\n' ~ "{{ fact_snapshot_published('" ~ marker ~ "') }}" ~ '\n']) -%}
        {%- do files.append([test_dir ~ '/' ~ marker ~ '__gates.sql',
                             header ~ '\n' ~ "{{ fact_snapshot_gate_test('" ~ marker ~ "') }}" ~ '\n']) -%}
    {%- endfor -%}

    {%- set docs_lines = [] -%}
    {%- do docs_lines.append('version: 2') -%}
    {%- do docs_lines.append('') -%}
    {%- do docs_lines.append('models:') -%}
    {%- for marker in markers -%}
        {%- do docs_lines.append('  - name: ' ~ marker ~ '__history') -%}
        {%- do docs_lines.append('    description: "Generated periodic snapshot fact history model for ' ~ marker ~ '."') -%}
        {%- do docs_lines.append('  - name: ' ~ marker ~ '__published') -%}
        {%- do docs_lines.append('    description: "Generated approval-gated published view for ' ~ marker ~ '."') -%}
    {%- endfor -%}
    {%- do files.append([docs_yaml_path, (docs_lines | join('\n')) ~ '\n']) -%}

    {%- if write_file is defined -%}

        {%- for f in files -%}
            {%- do write_file(f[1], f[0], true) -%}
        {%- endfor -%}
        {%- do log('fact_snapshot_generate_shims: wrote ' ~ (files | length) ~ ' file(s) for ' ~
                   (markers | length) ~ ' fact(s)', info=True) -%}

    {%- else -%}

        {#- stock dbt-core: print a POSIX script that creates the files.
            Apply with: dbt --quiet run-operation fact_snapshot_generate_shims | sh -#}
        {%- set out = [] -%}
        {%- do out.append('# generated by fact_snapshot_generate_shims for ' ~ (markers | length) ~
                          ' fact(s); apply with:') -%}
        {%- do out.append('#   dbt --quiet run-operation fact_snapshot_generate_shims | sh') -%}
        {%- do out.append('set -e') -%}
        {%- do out.append('mkdir -p ' ~ model_dir ~ ' ' ~ test_dir) -%}
        {%- for f in files -%}
            {%- do out.append("cat > '" ~ f[0] ~ "' <<'FACT_SHIM_EOF'") -%}
            {%- do out.append(f[1] | trim) -%}
            {%- do out.append('FACT_SHIM_EOF') -%}
            {%- do out.append("echo 'wrote " ~ f[0] ~ "'") -%}
        {%- endfor -%}
        {%- do print(out | join('\n')) -%}

    {%- endif -%}
{% endmacro %}
