/*
    scd2_generate_shims
    -------------------
    dbt-native shim generation for SCD2 dimensions.

    Instead of manually creating model files per dimension, define dimensions
    once in vars.scd2_dimensions and run:

      dbt run-operation scd2_generate_shims                    # write_file runtimes
      dbt --quiet run-operation scd2_generate_shims | sh       # stock dbt-core

    This writes (or updates) one-line shim files:
      - models/scd2/generated/<name>__history.sql
      - models/scd2/generated/<name>__candidate.sql
      - models/scd2/generated/<name>__published.sql
      - tests/generated/<name>__gates.sql

    Optional docs yaml is also generated:
      - models/scd2/generated/scd2_generated_models.yml

    Runtime note: stock dbt-core exposes no file-write context function to
    Jinja (write() is model-only), so on standard runtimes the macro prints
    a POSIX script that creates the files - pipe it through sh from the
    project root (--quiet keeps dbt's own logging out of the script; drop
    the "| sh" to review first). If your runtime does provide write_file,
    the macro writes the files directly and the hook below keeps them in
    sync:

      on-run-start:
        - "{{ scd2_generate_shims() }}"

    Either way, dbt parses the project BEFORE on-run-start executes, so
    newly generated shims are picked up by the NEXT invocation, not the one
    that generated them.
*/

{% macro scd2_dimension_markers() %}
    {%- set dims = var('scd2_dimensions', []) -%}
    {%- set markers = [] -%}
    {%- for d in dims -%}
        {%- if not d.get('name') -%}
            {{ exceptions.raise_compiler_error(
                "scd2_generate_shims: every vars.scd2_dimensions entry must define 'name'.") }}
        {%- endif -%}
        {%- if not modules.re.match('^[A-Za-z][A-Za-z0-9_]*$', d.get('name')) -%}
            {{ exceptions.raise_compiler_error(
                "scd2_generate_shims: dimension name '" ~ d.get('name') ~
                "' must match ^[A-Za-z][A-Za-z0-9_]*$ (it becomes file and table names).") }}
        {%- endif -%}
        {%- if not d.get('source') or not d.get('natural_key') -%}
            {{ exceptions.raise_compiler_error(
                "scd2_generate_shims: dimension '" ~ d.get('name') ~
                "' must define both 'source' and 'natural_key'.") }}
        {%- endif -%}
        {%- if d.get('name') not in markers -%}
            {%- do markers.append(d.get('name')) -%}
        {%- endif -%}
    {%- endfor -%}
    {%- do return(markers) -%}
{% endmacro %}


{% macro scd2_generate_shims(
    model_dir='models/scd2/generated',
    test_dir='tests/generated',
    docs_yaml_path='models/scd2/generated/scd2_generated_models.yml'
) %}
    {%- if not execute -%}
        {%- do return(none) -%}
    {%- endif -%}

    {%- set markers = scd2_dimension_markers() -%}
    {%- set header = '-- generated by dbt run-operation scd2_generate_shims' -%}

    {#- assemble every file as [path, content] so both write paths share it -#}
    {%- set files = [] -%}
    {%- for marker in markers -%}
        {%- do files.append([model_dir ~ '/' ~ marker ~ '__history.sql',
                             header ~ '\n' ~ "{{ scd2_history('" ~ marker ~ "') }}" ~ '\n']) -%}
        {%- do files.append([model_dir ~ '/' ~ marker ~ '__candidate.sql',
                             header ~ '\n' ~ "{{ scd2_candidate('" ~ marker ~ "') }}" ~ '\n']) -%}
        {%- do files.append([model_dir ~ '/' ~ marker ~ '__published.sql',
                             header ~ '\n' ~ "{{ scd2_published('" ~ marker ~ "') }}" ~ '\n']) -%}
        {%- do files.append([test_dir ~ '/' ~ marker ~ '__gates.sql',
                             header ~ '\n' ~ "{{ scd2_gate_test('" ~ marker ~ "') }}" ~ '\n']) -%}
    {%- endfor -%}

    {%- set docs_lines = [] -%}
    {%- do docs_lines.append('version: 2') -%}
    {%- do docs_lines.append('') -%}
    {%- do docs_lines.append('models:') -%}
    {%- for marker in markers -%}
        {%- do docs_lines.append('  - name: ' ~ marker ~ '__history') -%}
        {%- do docs_lines.append('    description: "Generated SCD2 insert-only history model for ' ~ marker ~ '."') -%}
        {%- do docs_lines.append('  - name: ' ~ marker ~ '__candidate') -%}
        {%- do docs_lines.append('    description: "Generated SCD2 candidate view (approved + pending) for ' ~ marker ~ '."') -%}
        {%- do docs_lines.append('  - name: ' ~ marker ~ '__published') -%}
        {%- do docs_lines.append('    description: "Generated SCD2 approval-gated published view for ' ~ marker ~ '."') -%}
    {%- endfor -%}
    {%- do files.append([docs_yaml_path, (docs_lines | join('\n')) ~ '\n']) -%}

    {%- if write_file is defined -%}

        {%- for f in files -%}
            {%- do write_file(f[1], f[0], true) -%}
        {%- endfor -%}
        {%- do log('scd2_generate_shims: wrote ' ~ (files | length) ~ ' file(s) for ' ~
                   (markers | length) ~ ' dimension(s)', info=True) -%}

    {%- else -%}

        {#- stock dbt-core: print a POSIX script that creates the files.
            Apply with: dbt --quiet run-operation scd2_generate_shims | sh -#}
        {%- set out = [] -%}
        {%- do out.append('# generated by scd2_generate_shims for ' ~ (markers | length) ~
                          ' dimension(s); apply with:') -%}
        {%- do out.append('#   dbt --quiet run-operation scd2_generate_shims | sh') -%}
        {%- do out.append('set -e') -%}
        {%- do out.append('mkdir -p ' ~ model_dir ~ ' ' ~ test_dir) -%}
        {%- for f in files -%}
            {%- do out.append("cat > '" ~ f[0] ~ "' <<'DBT_SHIM_EOF'") -%}
            {%- do out.append(f[1] | trim) -%}
            {%- do out.append('DBT_SHIM_EOF') -%}
            {%- do out.append("echo 'wrote " ~ f[0] ~ "'") -%}
        {%- endfor -%}
        {%- do print(out | join('\n')) -%}

    {%- endif -%}
{% endmacro %}
